
# Window
window_padding_width 0 5
background_opacity 0.98
hide_window_decorations no
scrollback_indicator_opacity 0.0

# Cursor
cursor_trail 1
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# Behavior
enable_audio_bello no
confirm_os_window_close 0
allow_remote_control yes

# Colors
background #0a0a0a
foreground #c7ccd1
cursor-color #c0c0c0
selection-foreground #0a0a0a
selection-background #c0c0c0

# black
color0  #111111
color8  #5c6370

# red
color1  #c4746e
color9  #e46876

# green
color2  #8a9a7b
color10 #a3be8c

# yellow
color3  #c4b28a
color11 #e5c07b

# blue
color4  #7fbbb3
color12 #89dceb

# magenta
color5  #a292a3
color13 #cba6f7

# cyan
color6  #8ea4a2
color14 #94e2d5

# white
color7  #c7ccd1
color15 #ffffff

# Tabs
active_tab_background   #7aa2f7
active_tab_foreground   #0b0f14
inactive_tab_background #16161e
inactive_tab_foreground #7f8490


# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 		  10
# END_KITTY_FONTS
